# These are supported funding model platforms

# github: [username] # Replace with your GitHub username
# patreon: username
# open_collective: happy-chat-kit
# ko_fi: username
# tidelift: npm/happy-chat-kit
# custom: ['https://example.com/donate']
